#PATH := /usr/local/bin:$(PATH)

all:
	platformio  run

upload:
	platformio  run --target upload

clean:
	platformio  run --target clean

program:
	platformio  run --target program

update:
	platformio  update
